import { useEffect, useState } from "react";
import { Link, useLocation, useSearch } from "wouter";
import { ArrowDownToLine, ArrowRight, BadgeCheck, Bell, Building2, Check, CircleAlert, CircleDollarSign, FileText, Search, ShieldCheck, SlidersHorizontal, Users, Wallet } from "lucide-react";
import { formatPrice } from "@/data/demo";
import { useDemo } from "@/components/DemoStore";

const tabs = [
  { id: "vue", label: "Vue d’ensemble", icon: CircleDollarSign },
  { id: "annonces", label: "Annonces", icon: Building2 },
  { id: "utilisateurs", label: "Utilisateurs", icon: Users },
  { id: "reservations", label: "Réservations", icon: FileText },
  { id: "finances", label: "Finances", icon: Wallet },
  { id: "signalements", label: "Signalements", icon: CircleAlert },
  { id: "verifications", label: "Vérifications", icon: BadgeCheck },
  { id: "contenus", label: "Contenus & notifications", icon: Bell },
  { id: "parametres", label: "Paramètres métier", icon: SlidersHorizontal },
  { id: "audit", label: "Journal d’audit", icon: ShieldCheck },
];

export default function AdminPage() {
  const { properties, bookings, demoFee, setDemoFee, notify } = useDemo();
  const [location] = useLocation();
  const searchString = useSearch();
  const params = new URLSearchParams(searchString);
  const [tab, setTab] = useState(params.get("section") ?? "vue");
  const [search, setSearch] = useState("");
  const [moderation, setModeration] = useState<Record<string, string>>({});
  const [disputes, setDisputes] = useState<Record<string, string>>({});
  useEffect(() => {
    const section = new URLSearchParams(searchString).get("section") ?? "vue";
    if (tabs.some((item) => item.id === section)) setTab(section);
  }, [location, searchString]);
  const selectedLabel = tabs.find((item) => item.id === tab)?.label ?? "Vue d’ensemble";
  const demoPayments = [{ id: "PAY-8841", person: "Aïcha D.", listing: "La terrasse de Fidjrossè", total: 134000, status: "Confirmé · démo", date: "06 oct. 2026" }, { id: "PAY-8837", person: "Sékou A.", listing: "Le studio des bonnes adresses", total: 52000, status: "En attente · démo", date: "05 oct. 2026" }, { id: "PAY-8829", person: "Mireille H.", listing: "La chambre claire de Calavi", total: 240000, status: "Demande · démo", date: "04 oct. 2026" }];

  function action(key: string, label: string) {
    setModeration((items) => ({ ...items, [key]: label }));
    notify(`${label} enregistré en démonstration. Aucun changement réel.`);
  }

  return <section className="admin-page content-section"><div className="admin-heading"><div><span className="eyebrow">ADMINISTRATION · ENVIRONNEMENT FICTIF</span><h1>ICIMO, côté coulisses.</h1><p>Outils d’exemple pour gérer le marché · aucune opération n’est exécutée.</p></div><span className="status-pill status-confirmed"><i className="demo-dot" /> Mode démo actif</span></div><div className="admin-overview-metrics"><article><span>Utilisateurs fictifs</span><strong>1 284</strong><small>+8,4 % ce mois-ci</small></article><article><span>Annonces publiées</span><strong>{properties.length + 38}</strong><small>12 en attente · exemple</small></article><article><span>Réservations</span><strong>{bookings.length + 126}</strong><small>91 % confirmées · exemple</small></article><article><span>Volume indicatif</span><strong>{formatPrice(42500000)}</strong><small>Transactions entièrement fictives</small></article></div><div className="admin-console"><aside className="admin-sidenav">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? "active" : ""} onClick={() => { setTab(id); window.history.replaceState({}, "", id === "vue" ? "/admin" : `/admin?section=${id}`); }}><Icon size={17} />{label}{id === "annonces" && <i>12</i>}{id === "signalements" && <i className="alert-count">3</i>}</button>)}<div className="admin-sidenav-note"><ShieldCheck size={16} /><span>Les permissions réelles et le journal d’audit devront être garantis côté serveur.</span></div></aside><div className="admin-content"><div className="admin-content-heading"><div><span className="eyebrow">CENTRE DE CONTRÔLE</span><h2>{selectedLabel}</h2></div><label className="admin-search"><Search size={16} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher dans la démo" /></label></div>

{tab === "vue" && <><div className="admin-welcome-band"><div><span className="eyebrow eyebrow-light">MARDI · 6 OCTOBRE 2026</span><h2>Bonjour, équipe ICIMO.</h2><p>Voici ce qui se passe dans l’espace de démonstration.</p></div><div className="admin-welcome-badge"><span>Commission d’exemple</span><strong>{demoFee} %</strong></div></div><div className="admin-two-cols"><section className="admin-panel"><div className="panel-heading"><div><h3>À examiner</h3><p>Éléments de modération fictifs</p></div><CircleAlert size={19} /></div>{properties.slice(0, 3).map((property, index) => <div className="admin-task-row" key={property.slug}><span className="admin-task-icon">{index === 0 ? <Building2 size={16} /> : <BadgeCheck size={16} />}</span><div><strong>{index === 0 ? "Annonce à vérifier" : index === 1 ? "Identité à examiner" : "Signalement de contenu"}</strong><small>{property.title} · {property.city}</small></div><button onClick={() => setTab("annonces")}>Examiner <ArrowRight size={13} /></button></div>)}</section><section className="admin-panel"><div className="panel-heading"><div><h3>Derniers mouvements</h3><p>Journal de démonstration</p></div><Link className="text-link" href="/admin?section=audit">Tout voir</Link></div>{["Paiement PAY-8841 · succès simulé", "Annonce terrasse-fidjrosse · vérifiée en démo", "Rôle propriétaire · modification illustrative"].map((item, index) => <div key={item} className="audit-line"><i className={index === 0 ? "audit-dot green" : "audit-dot"} /><span>{item}</span><small>{index === 0 ? "09:41" : index === 1 ? "09:18" : "Hier"}</small></div>)}</section></div></>}

{tab === "annonces" && <section className="admin-panel"><div className="panel-heading"><div><h3>Modération des annonces</h3><p>Valider, corriger ou retirer · interactions locales seulement.</p></div><span className="status-pill status-request">12 à examiner · fictif</span></div><div className="table-wrap"><table><thead><tr><th>Annonce</th><th>Propriétaire</th><th>Type</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{properties.filter((property) => `${property.title} ${property.city}`.toLowerCase().includes(search.toLowerCase())).map((property, index) => <tr key={property.slug}><td><div className="admin-listing-cell"><img src={property.image} alt="" /><span><strong>{property.title}</strong><small>{property.district}, {property.city}</small></span></div></td><td>{property.owner}</td><td>{property.kind === "long" ? "Au mois" : property.kind === "both" ? "Mixte" : "Courte durée"}</td><td><span className="status-pill status-confirmed">{moderation[property.slug] ?? (index === 0 ? "À valider · démo" : "Publiée · démo")}</span></td><td><div className="table-actions"><button onClick={() => action(property.slug, "Validée · démo")} aria-label="Valider l’annonce">✓</button><button onClick={() => action(property.slug, "À corriger · démo")} aria-label="Demander une correction">Corriger</button><button onClick={() => action(property.slug, "Retirée · démo")} aria-label="Retirer l’annonce">Retirer</button></div></td></tr>)}</tbody></table></div></section>}

{tab === "utilisateurs" && <section className="admin-panel"><div className="panel-heading"><div><h3>Comptes et rôles</h3><p>Rôles fictifs : client, propriétaire, support, finance, super administrateur.</p></div><span className="status-pill">Permissions · démo</span></div><div className="table-wrap"><table><thead><tr><th>Utilisateur</th><th>Contact</th><th>Rôle</th><th>Vérification</th><th>État de démo</th></tr></thead><tbody>{[{ name: "Aïcha Dossou", email: "aicha.dossou@example.com", role: "Client · Propriétaire", state: "Actif · démo" }, { name: "Mina A.", email: "mina.hote@example.com", role: "Propriétaire", state: "Actif · démo" }, { name: "Equipe Support", email: "support@icimo.demo", role: "Support", state: "Rôle illustratif" }].filter((item) => item.name.toLowerCase().includes(search.toLowerCase())).map((person) => <tr key={person.name}><td><strong>{person.name}</strong></td><td>{person.email}</td><td><select defaultValue={person.role} onChange={() => action(person.name, "Rôle modifié · démo")}><option>Client</option><option>Propriétaire</option><option>Client · Propriétaire</option><option>Support</option><option>Finance</option><option>Super administrateur</option></select></td><td><span className="status-pill status-confirmed">À confirmer</span></td><td>{person.state}</td></tr>)}</tbody></table></div><div className="demo-notice"><ShieldCheck size={17} /><span>La modification des rôles n’est qu’un aperçu ; un futur backend devra imposer les permissions.</span></div></section>}

{tab === "reservations" && <section className="admin-panel"><div className="panel-heading"><div><h3>Réservations & incidents</h3><p>Suivi d’exemple des demandes et séjours.</p></div><span className="status-pill status-request">Suivi de démo</span></div><div className="table-wrap"><table><thead><tr><th>Référence</th><th>Voyageur</th><th>Logement</th><th>Type</th><th>État</th><th>Actions</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking.id}><td>{booking.id}</td><td>Aïcha D.</td><td>{properties.find((property) => property.slug === booking.slug)?.title}</td><td>{booking.kind === "short" ? "Courte durée" : "Longue durée"}</td><td>{booking.status === "confirmed" ? "Confirmée · démo" : booking.status === "accepted" ? "Acceptée · bail à définir · démo" : booking.status === "declined" ? "Refusée · démo" : booking.status === "request" ? "Demande en cours · démo" : "En attente · démo"}</td><td><button className="text-button" onClick={() => action(booking.id, "Dossier examiné · démo")}>Ouvrir le dossier</button></td></tr>)}</tbody></table></div><div className="admin-panel-footer"><CircleAlert size={16} /><span>Les incidents et remboursements éventuels ne sont pas traités en réel.</span></div></section>}

{tab === "finances" && <section className="admin-panel"><div className="panel-heading"><div><h3>Paiements, commissions et versements</h3><p>Transactions fictives, aucune écriture comptable.</p></div><button className="button button-outline button-small" onClick={() => notify("Export indisponible : aucune base comptable n’est connectée.")}><ArrowDownToLine size={14} /> Exporter</button></div><div className="table-wrap"><table><thead><tr><th>Référence</th><th>Voyageur</th><th>Logement</th><th>Date</th><th>Total · démo</th><th>Statut</th></tr></thead><tbody>{demoPayments.filter((item) => item.id.toLowerCase().includes(search.toLowerCase()) || item.person.toLowerCase().includes(search.toLowerCase())).map((payment) => <tr key={payment.id}><td>{payment.id}</td><td>{payment.person}</td><td>{payment.listing}</td><td>{payment.date}</td><td>{formatPrice(payment.total)}</td><td><span className="status-pill status-confirmed">{payment.status}</span></td></tr>)}</tbody></table></div><Link href="/hote/revenus" className="admin-finance-link">Voir le suivi propriétaire des versements <ArrowRight size={14} /></Link></section>}

{tab === "signalements" && <section className="admin-panel"><div className="panel-heading"><div><h3>Signalements & risques</h3><p>File d’exemple pour abus, fraude potentielle et contenus litigieux.</p></div><span className="status-pill status-request">3 ouverts · démo</span></div>{[{ id: "REP-038", title: "Vérifier le contenu de l’annonce", detail: "La terrasse de Fidjrossè · reçu aujourd’hui", priority: "À examiner" }, { id: "REP-035", title: "Demande de contrôle propriétaire", detail: "Profil illustratif · reçue hier", priority: "Vérification" }, { id: "REP-031", title: "Question sur un paiement", detail: "Transaction fictive PAY-8837", priority: "Support" }].map((report) => <article className="report-row" key={report.id}><span className="report-symbol"><CircleAlert size={17} /></span><div><strong>{report.title}</strong><p>{report.detail} · {report.id}</p></div><span className="status-pill status-request">{disputes[report.id] ?? report.priority}</span><button className="button button-outline button-small" onClick={() => setDisputes((items) => ({ ...items, [report.id]: "Examiné · démo" }))}>Examiner</button></article>)}</section>}

{tab === "verifications" && <section className="admin-panel"><div className="panel-heading"><div><h3>Vérifications des propriétaires</h3><p>Décisions de modération fictives · aucun document sensible n’est chargé.</p></div><BadgeCheck size={18} /></div>{[{ id: "VER-210", name: "Mina A.", detail: "La terrasse de Fidjrossè · pièce d’identité · exemple" }, { id: "VER-204", name: "Josué D.", detail: "Le studio des bonnes adresses · justificatif · exemple" }].map((record) => <article className="report-row" key={record.id}><span className="report-symbol"><BadgeCheck size={17} /></span><div><strong>{record.name}</strong><p>{record.detail} · {record.id}</p></div><span className="status-pill status-request">{moderation[record.id] ?? "À examiner"}</span><button className="button button-primary button-small" onClick={() => action(record.id, "Validée · démo")}>Valider</button><button className="button button-outline button-small" onClick={() => action(record.id, "Complément demandé · démo")}>Complément</button></article>)}<div className="demo-notice"><ShieldCheck size={17} /><span>Un futur service devra conserver les pièces dans un stockage privé avec accès contrôlé.</span></div></section>}

{tab === "contenus" && <section className="admin-panel"><div className="panel-heading"><div><h3>Contenus et notifications</h3><p>Textes et messages visibles dans l’expérience ICIMO · tout est fictif.</p></div><Bell size={18} /></div><div className="content-admin-card"><label>Titre de l’information<input defaultValue="Bienvenue sur ICIMO" /></label><label>Message<input defaultValue="Explorez des locations courte et longue durée au Bénin." /></label><div className="business-setting-row"><span><strong>Bandeau de démonstration</strong><small>Visible en haut de l’interface · contenu exemple</small></span><select defaultValue="Actif" onChange={(e) => action("content-banner", `${e.target.value} · démo`)}><option>Actif</option><option>Masqué</option><option>Brouillon</option></select></div><div className="notification-admin-sample"><Bell size={17} /><span><strong>Rappel de réservation · exemple</strong><small>Votre séjour approche · notifications locale et fictive.</small></span><button className="button button-outline button-small" onClick={() => notify("Aperçu de notification : aucun message réel n’est envoyé.")}>Prévisualiser</button></div><button className="button button-primary button-small" onClick={() => action("content", "Contenu enregistré · démo")}>Enregistrer la version fictive</button></div></section>}

{tab === "parametres" && <section className="admin-panel business-settings"><div className="panel-heading"><div><h3>Paramètres métier</h3><p>Valeurs de démonstration modifiables sans changer le code.</p></div><SlidersHorizontal size={18} /></div><label className="fee-setting"><span><strong>Commission ICIMO</strong><small>Valeur utilisée uniquement par le calcul de réservation local.</small></span><div className="fee-slider"><input type="range" min="0" max="25" step="1" value={demoFee} onChange={(e) => setDemoFee(Number(e.target.value))} /><b>{demoFee} %</b></div></label><div className="fee-example"><span>Sur un hébergement de 100 000 F CFA</span><strong>{formatPrice(100000 * demoFee / 100)}</strong><small>Commission indicative · démonstration</small></div><div className="business-setting-row"><span><strong>Statut des paiements</strong><small>Prestataire de paiement non connecté</small></span><span className="status-pill status-request">Saspay.me · prévu</span></div><div className="business-setting-row"><span><strong>Devise affichée</strong><small>Préparation à l’expansion multi-pays ultérieurement</small></span><span className="status-pill">XOF · F CFA</span></div><button className="button button-primary" onClick={() => notify("Paramètres métier sauvegardés dans cette démonstration.")}>Enregistrer les paramètres · démo</button></section>}

{tab === "audit" && <section className="admin-panel"><div className="panel-heading"><div><h3>Journal d’audit illustratif</h3><p>Aperçu des traces qui devront être conservées pour les opérations sensibles.</p></div><ShieldCheck size={19} /></div>{["08:52 · Aïcha D. · aperçu d’une annonce", "09:18 · équipe ICIMO · vérification de démonstration", "09:41 · système simulé · paiement PAY-8841", "Hier · administrateur · consultation d’un signalement", "Hier · équipe finance · simulation d’un décaissement"].map((line) => <div className="audit-record" key={line}><span className="audit-record-dot" /><strong>{line.split(" · ")[0]}</strong><span>{line.split(" · ").slice(1).join(" · ")}</span><small>Événement de démonstration · non opposable</small></div>)}<div className="demo-notice"><ShieldCheck size={17} /><span>Le journal réel devra être signé côté serveur, contrôlé et conservé selon les règles métier.</span></div></section>}
</div></div></section>;
}
